### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by hongym7** [manigalati/usad#6]
I run this USAD.ipynb in jupyter-notebook.

train is ok.
test is error.
error message is below.

RuntimeError: CUDA out of memory. Tried to allocate 38.00 MiB (GPU 0; 10.76 GiB total capacity; 8.95 GiB already allocated; 17.06 MiB free; 9.61 GiB reserved in total by PyTorch)

=================================

How should I change the Parameter to solve this problem?

my gpu is GPU 0: GeForce RTX 2080 Ti, GPU 1: GeForce RTX 2080 Ti

Thank you.

**Comment by balllightnings** [comment]
hi, I found the same problem.
you can edit the code like this:
`with torch.no_grad():
  results=testing(model,test_loader)`

**Comment by zhaotianzi** [comment]
thank you very much.
I have solved the problem.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "manigalati/usad"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月19日(星期五) 上午10:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [manigalati/usad] RuntimeError: CUDA out of memory. (#6)





 
hi, I found the same problem.
 you can edit the code like this:
 with torch.no_grad(): results=testing(model,test_loader)
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
